(function (root) {
  const alphabet = [
    { id: 'a', upper: 'А', lower: 'а', group: 'vowel', name: 'a', speak: 'а', tr: 'a', hint: 'Como la a de «casa».', note: 'Casi no cambia entre sílaba tónica y átona.', example: { ru: 'мама', tr: 'MA-ma', es: 'mamá' } },
    { id: 'be', upper: 'Б', lower: 'б', group: 'consonant', name: 'be', speak: 'бэ', tr: 'be', hint: 'Como la b de «barco».', note: 'Los labios se cierran del todo.', example: { ru: 'банк', tr: 'BANK', es: 'banco' } },
    { id: 've', upper: 'В', lower: 'в', group: 'consonant', name: 've', speak: 'вэ', tr: 've', hint: 'Como la v inglesa: el aire pasa entre los labios.', note: 'No es la b española. Piensa en «vino» dicho con labios juntos.', example: { ru: 'вода', tr: 'va-DA', es: 'agua' } },
    { id: 'ge', upper: 'Г', lower: 'г', group: 'consonant', name: 'ge', speak: 'гэ', tr: 'ge', hint: 'Como la g de «gato». Nunca como la j.', note: 'Al final de palabra suele sonar k: друг suena «druk».', example: { ru: 'город', tr: 'GO-rat', es: 'ciudad' } },
    { id: 'de', upper: 'Д', lower: 'д', group: 'consonant', name: 'de', speak: 'дэ', tr: 'de', hint: 'Como la d de «dedo», con la lengua en los dientes.', note: 'Al final de palabra suele sonar t: город suena «gorat».', example: { ru: 'дом', tr: 'DOM', es: 'casa' } },
    { id: 'ye', upper: 'Е', lower: 'е', group: 'vowel', name: 'ye', speak: 'йэ', tr: 'ye', hint: 'Al inicio o tras vocal suena «ye», como en «yeso».', note: 'Tras consonante suena «e» y ablanda esa consonante.', example: { ru: 'если', tr: 'YES-li', es: 'si' } },
    { id: 'yo', upper: 'Ё', lower: 'ё', group: 'vowel', name: 'yo', speak: 'йо', tr: 'yo', hint: 'Siempre «yo», y casi siempre es la sílaba tónica.', note: 'En muchos textos se escribe е, pero se pronuncia yo.', example: { ru: 'ёлка', tr: 'YOL-ka', es: 'abeto' } },
    { id: 'zhe', upper: 'Ж', lower: 'ж', group: 'consonant', name: 'zhe', speak: 'жэ', tr: 'zhe', hint: 'Como la j francesa, o la s sonora de la palabra inglesa «leisure».', note: 'La lengua va un poco hacia atrás. Siempre es fuerte, no se ablanda.', example: { ru: 'жена', tr: 'zhe-NA', es: 'esposa' } },
    { id: 'ze', upper: 'З', lower: 'з', group: 'consonant', name: 'ze', speak: 'зэ', tr: 'ze', hint: 'Como la z inglesa, o la s de «desde» en España.', note: 'Las cuerdas vocales vibran. No es la z de «zapato» del centro de España.', example: { ru: 'завтра', tr: 'ZAF-tra', es: 'mañana' } },
    { id: 'i', upper: 'И', lower: 'и', group: 'vowel', name: 'i', speak: 'и', tr: 'i', hint: 'Como la i de «iris».', note: 'Es la vocal más parecida al español.', example: { ru: 'имя', tr: 'IM-ya', es: 'nombre' } },
    { id: 'ikrat', upper: 'Й', lower: 'й', group: 'consonant', name: 'i kratkoye', speak: 'и краткое', tr: 'y', hint: 'Una i muy breve, como la y de «rey».', note: 'Casi nunca va sola. Cierra diptongos: мой suena «moy».', example: { ru: 'мой', tr: 'MOY', es: 'mi' } },
    { id: 'ka', upper: 'К', lower: 'к', group: 'consonant', name: 'ka', speak: 'ка', tr: 'ka', hint: 'Como la c de «casa» o la k.', note: 'No se aspira.', example: { ru: 'кот', tr: 'KOT', es: 'gato' } },
    { id: 'el', upper: 'Л', lower: 'л', group: 'consonant', name: 'el', speak: 'эль', tr: 'el', hint: 'Como la l de «luna».', note: 'Con ь detrás se ablanda: сильнее.', example: { ru: 'лампа', tr: 'LAM-pa', es: 'lámpara' } },
    { id: 'em', upper: 'М', lower: 'м', group: 'consonant', name: 'em', speak: 'эм', tr: 'em', hint: 'Como la m de «mamá».', note: 'Igual que en español.', example: { ru: 'море', tr: 'MO-rye', es: 'mar' } },
    { id: 'en', upper: 'Н', lower: 'н', group: 'consonant', name: 'en', speak: 'эн', tr: 'en', hint: 'Como la n de «nada».', note: 'Con ь se acerca a la ñ: день.', example: { ru: 'нет', tr: 'NYET', es: 'no' } },
    { id: 'o', upper: 'О', lower: 'о', group: 'vowel', name: 'o', speak: 'о', tr: 'o', hint: 'Si es tónica, como la o de «oso».', note: 'Si no lleva el acento, se acerca a «a»: молоко suena «malako».', example: { ru: 'он', tr: 'ON', es: 'él' } },
    { id: 'pe', upper: 'П', lower: 'п', group: 'consonant', name: 'pe', speak: 'пэ', tr: 'pe', hint: 'Como la p de «pan».', note: 'No se aspira.', example: { ru: 'папа', tr: 'PA-pa', es: 'papá' } },
    { id: 'er', upper: 'Р', lower: 'р', group: 'consonant', name: 'er', speak: 'эр', tr: 'er', hint: 'R vibrante, como la rr de «perro».', note: 'Una sola р ya vibra. No existe la r suave española.', example: { ru: 'рот', tr: 'ROT', es: 'boca' } },
    { id: 'es', upper: 'С', lower: 'с', group: 'consonant', name: 'es', speak: 'эс', tr: 'es', hint: 'Como la s de «sol».', note: 'Nunca como la z castellana.', example: { ru: 'сон', tr: 'SON', es: 'sueño' } },
    { id: 'te', upper: 'Т', lower: 'т', group: 'consonant', name: 'te', speak: 'тэ', tr: 'te', hint: 'Como la t de «toma»; la lengua toca los dientes.', note: 'Más dental que la t inglesa.', example: { ru: 'тут', tr: 'TUT', es: 'aquí' } },
    { id: 'u', upper: 'У', lower: 'у', group: 'vowel', name: 'u', speak: 'у', tr: 'u', hint: 'Como la u de «uva».', note: 'Los labios se redondean.', example: { ru: 'утро', tr: 'UT-ra', es: 'mañana' } },
    { id: 'ef', upper: 'Ф', lower: 'ф', group: 'consonant', name: 'ef', speak: 'эф', tr: 'ef', hint: 'Como la f de «foca».', note: 'Igual que en español.', example: { ru: 'фото', tr: 'FO-ta', es: 'foto' } },
    { id: 'ja', upper: 'Х', lower: 'х', group: 'consonant', name: 'ja', speak: 'ха', tr: 'ja', hint: 'Como la j de «jamón», un poco más suave.', note: 'Sale del fondo de la boca, sin ser tan rasposa como la j fuerte.', example: { ru: 'хлеб', tr: 'KHLEP', es: 'pan' } },
    { id: 'tse', upper: 'Ц', lower: 'ц', group: 'consonant', name: 'tse', speak: 'цэ', tr: 'tse', hint: 'Como ts en «tsunami»: t y s juntas.', note: 'Una sola consonante, no dos letras sueltas.', example: { ru: 'центр', tr: 'TSENTR', es: 'centro' } },
    { id: 'che', upper: 'Ч', lower: 'ч', group: 'consonant', name: 'che', speak: 'че', tr: 'che', hint: 'Como la ch de «chico».', note: 'Siempre suave.', example: { ru: 'чай', tr: 'CHAY', es: 'té' } },
    { id: 'sha', upper: 'Ш', lower: 'ш', group: 'consonant', name: 'sha', speak: 'ша', tr: 'sha', hint: 'Como sh en «show», con la lengua más atrás.', note: 'Siempre fuerte. No es la ch española.', example: { ru: 'школа', tr: 'SHKO-la', es: 'escuela' } },
    { id: 'shcha', upper: 'Щ', lower: 'щ', group: 'consonant', name: 'shcha', speak: 'ща', tr: 'shcha', hint: 'Más larga y suave que ш. Algo como «shch».', note: 'La lengua se acerca al paladar. Piensa en una sh prolongada.', example: { ru: 'щи', tr: 'SHCHI', es: 'sopa de col' } },
    { id: 'duro', upper: 'Ъ', lower: 'ъ', group: 'sign', name: 'signo duro', speak: 'твёрдый знак', tr: '—', hint: 'No se pronuncia. Separa una consonante de ye, ya o yo.', note: 'Marca una pausa mínima: подъезд suena «pad-yezd», no «padyezd» fundido.', example: { ru: 'подъезд', tr: 'pad-YEZD', es: 'portal' } },
    { id: 'y', upper: 'Ы', lower: 'ы', group: 'vowel', name: 'y', speak: 'ы', tr: 'y', hint: 'Entre i y u, con la lengua atrás. No existe en español.', note: 'Di una i con la boca de u, sin redondear los labios. Aparece en ты, мы, вы.', example: { ru: 'ты', tr: 'TY', es: 'tú' } },
    { id: 'blando', upper: 'Ь', lower: 'ь', group: 'sign', name: 'signo blando', speak: 'мягкий знак', tr: '—', hint: 'No suena solo. Ablanda la consonante anterior.', note: 'нь se acerca a ñ. мать suena «mat» con una t blanda.', example: { ru: 'мать', tr: "MAT'", es: 'madre' } },
    { id: 'e', upper: 'Э', lower: 'э', group: 'vowel', name: 'e', speak: 'э', tr: 'e', hint: 'Como la e de «eco», sin el sonido ye.', note: 'Menos frecuente que е. Abre la boca sin añadir una y.', example: { ru: 'это', tr: 'E-ta', es: 'esto' } },
    { id: 'yu', upper: 'Ю', lower: 'ю', group: 'vowel', name: 'yu', speak: 'ю', tr: 'yu', hint: 'Como «yu» en «yuca».', note: 'Tras consonante, la ablanda y suena «u».', example: { ru: 'юг', tr: 'YUK', es: 'sur' } },
    { id: 'ya', upper: 'Я', lower: 'я', group: 'vowel', name: 'ya', speak: 'я', tr: 'ya', hint: 'Como «ya» en «yate».', note: 'También es el pronombre «yo».', example: { ru: 'я', tr: 'YA', es: 'yo' } }
  ];

  const decks = [
    {
      id: 'saludos',
      title: 'Saludos',
      glyph: 'П',
      blurb: 'Entrar, salir y ser amable.',
      cards: [
        { id: 'saludos-01', ru: 'Привет', tr: 'pri-VYET', latin: 'privet', es: 'Hola', note: 'Informal, con amigos.' },
        { id: 'saludos-02', ru: 'Здравствуйте', tr: 'ZDRAST-vuy-tye', latin: 'zdravstvuyte', es: 'Hola (formal)', aliasesEs: ['hola', 'saludo formal'], aliasesRu: ['zdrastvuyte'], note: 'Para desconocidos, trabajo o respeto. Vale a cualquier hora.' },
        { id: 'saludos-03', ru: 'Доброе утро', tr: 'DO-bra-ye UT-ra', latin: 'dobroe utro', es: 'Buenos días', note: 'Hasta cerca del mediodía.' },
        { id: 'saludos-04', ru: 'Добрый день', tr: "DO-bry DYEN'", latin: 'dobryy den', es: 'Buen día', note: 'El saludo de la parte central del día.' },
        { id: 'saludos-05', ru: 'Добрый вечер', tr: 'DO-bry VYE-cher', latin: 'dobryy vecher', es: 'Buenas tardes', note: 'Al atardecer y por la noche, al llegar.' },
        { id: 'saludos-06', ru: 'Спокойной ночи', tr: 'spa-KOY-nay NO-chi', latin: 'spokoynoy nochi', es: 'Buenas noches', note: 'Al despedirse para ir a dormir.' },
        { id: 'saludos-07', ru: 'До свидания', tr: 'da svi-DA-ni-ya', latin: 'do svidaniya', es: 'Adiós', aliasesEs: ['hasta luego'], note: 'Despedida neutra. La о de до suena casi «a».' },
        { id: 'saludos-08', ru: 'Пока', tr: 'pa-KA', latin: 'poka', es: 'Chao', aliasesEs: ['hasta luego'], note: 'Informal.' },
        { id: 'saludos-09', ru: 'Спасибо', tr: 'spa-SÍ-ba', latin: 'spasibo', es: 'Gracias' },
        { id: 'saludos-10', ru: 'Пожалуйста', tr: 'pa-ZHA-luy-sta', latin: 'pozhaluysta', es: 'Por favor / de nada', note: 'Sirve para pedir y para responder a gracias.' },
        { id: 'saludos-11', ru: 'Извините', tr: 'iz-vi-NÍ-tye', latin: 'izvinite', es: 'Disculpe', aliasesEs: ['perdón', 'perdone'], note: 'Formal. Con amigos se oye извини (iz-vi-NÍ).' },
        { id: 'saludos-12', ru: 'Как дела?', tr: 'kak dye-LA', latin: 'kak dela', es: '¿Qué tal?', aliasesEs: ['cómo estás', 'como estas', 'qué tal'] },
        { id: 'saludos-13', ru: 'Хорошо', tr: 'kha-ra-SHO', latin: 'khorosho', es: 'Bien', aliasesEs: ['estoy bien'] },
        { id: 'saludos-14', ru: 'Меня зовут', tr: 'mye-NYA za-VUT', latin: 'menya zovut', es: 'Me llamo', note: 'Detrás va tu nombre.' },
        { id: 'saludos-15', ru: 'Как вас зовут?', tr: 'kak vas za-VUT', latin: 'kak vas zovut', es: '¿Cómo se llama?', aliasesEs: ['cómo se llama', 'como se llama'], note: 'Usted. Informal: Как тебя зовут?' },
        { id: 'saludos-16', ru: 'Очень приятно', tr: "O-chen' pri-YAT-na", latin: 'ochen priyatno', es: 'Mucho gusto' },
        { id: 'saludos-17', ru: 'Да', tr: 'DA', latin: 'da', es: 'Sí' },
        { id: 'saludos-18', ru: 'Нет', tr: 'NYET', latin: 'net', es: 'No' }
      ]
    },
    {
      id: 'frases',
      title: 'Frases',
      glyph: 'Я',
      blurb: 'Cuando aún no puedes conversar.',
      cards: [
        { id: 'frases-01', ru: 'Я не понимаю', tr: 'ya nye pa-ni-MA-yu', latin: 'ya ne ponimayu', es: 'No entiendo' },
        { id: 'frases-02', ru: 'Повторите, пожалуйста', tr: 'paf-ta-RÍ-tye, pa-ZHA-luy-sta', latin: 'povtorite pozhaluysta', es: 'Repita, por favor', aliasesEs: ['repítalo por favor'] },
        { id: 'frases-03', ru: 'Говорите медленнее', tr: 'ga-va-RÍ-tye MYED-lye-nye-ye', latin: 'govorite medlennee', es: 'Hable más despacio', aliasesEs: ['más despacio', 'mas despacio'] },
        { id: 'frases-04', ru: 'Я учу русский', tr: 'ya u-CHU RUS-kiy', latin: 'ya uchu russkiy', es: 'Estoy aprendiendo ruso', aliasesEs: ['aprendo ruso'] },
        { id: 'frases-05', ru: 'Как это по-русски?', tr: 'kak E-ta pa-RUS-ki', latin: 'kak eto po-russki', es: '¿Cómo se dice en ruso?', aliasesEs: ['cómo se dice en ruso'] },
        { id: 'frases-06', ru: 'Где туалет?', tr: 'gdye tua-LYET', latin: 'gde tualet', es: '¿Dónde está el baño?', aliasesEs: ['dónde está el baño', 'donde esta el servicio'] },
        { id: 'frases-07', ru: 'Сколько это стоит?', tr: 'SKOL-ka E-ta STO-it', latin: 'skolko eto stoit', es: '¿Cuánto cuesta?', aliasesEs: ['cuánto cuesta', 'cuanto cuesta'] },
        { id: 'frases-08', ru: 'Я испанец', tr: 'ya is-PA-nyets', latin: 'ya ispanets', es: 'Soy español', note: 'Forma masculina. Femenino: Я испанка (ya is-PAN-ka).' },
        { id: 'frases-09', ru: 'Помогите', tr: 'pa-ma-GÍ-tye', latin: 'pomogite', es: 'Ayúdeme', aliasesEs: ['ayuda', 'ayúdame'] },
        { id: 'frases-10', ru: 'Всё хорошо', tr: 'FSYO kha-ra-SHO', latin: 'vsyo khorosho', es: 'Todo está bien', aliasesEs: ['todo bien'], aliasesRu: ['vse khorosho'] },
        { id: 'frases-11', ru: 'Можно?', tr: 'MOZH-na', latin: 'mozhno', es: '¿Se puede?', aliasesEs: ['puedo', 'se puede'], note: 'Para pedir permiso.' },
        { id: 'frases-12', ru: 'Не знаю', tr: 'nye ZNA-yu', latin: 'ne znayu', es: 'No sé' }
      ]
    },
    {
      id: 'numeros',
      title: 'Números',
      glyph: '1',
      blurb: 'Del 1 al 20.',
      cards: [
        { id: 'numeros-01', ru: 'один', tr: 'a-DIN', latin: 'odin', es: 'uno', digit: 1, aliasesEs: ['un'], note: 'Masculino. Femenino: одна (ad-NA).' },
        { id: 'numeros-02', ru: 'два', tr: 'DVA', latin: 'dva', es: 'dos', digit: 2, note: 'Masculino. Femenino: две (DVYE).' },
        { id: 'numeros-03', ru: 'три', tr: 'TRI', latin: 'tri', es: 'tres', digit: 3 },
        { id: 'numeros-04', ru: 'четыре', tr: 'chi-TY-rye', latin: 'chetyre', es: 'cuatro', digit: 4 },
        { id: 'numeros-05', ru: 'пять', tr: "PYAT'", latin: 'pyat', es: 'cinco', digit: 5 },
        { id: 'numeros-06', ru: 'шесть', tr: "SHEST'", latin: 'shest', es: 'seis', digit: 6 },
        { id: 'numeros-07', ru: 'семь', tr: "SYEM'", latin: 'sem', es: 'siete', digit: 7 },
        { id: 'numeros-08', ru: 'восемь', tr: "VO-syem'", latin: 'vosem', es: 'ocho', digit: 8 },
        { id: 'numeros-09', ru: 'девять', tr: "DYE-vyat'", latin: 'devyat', es: 'nueve', digit: 9 },
        { id: 'numeros-10', ru: 'десять', tr: "DYE-syat'", latin: 'desyat', es: 'diez', digit: 10 },
        { id: 'numeros-11', ru: 'одиннадцать', tr: 'a-DÍ-na-tsat', latin: 'odinnadtsat', es: 'once', digit: 11 },
        { id: 'numeros-12', ru: 'двенадцать', tr: 'dvi-NA-tsat', latin: 'dvenadtsat', es: 'doce', digit: 12 },
        { id: 'numeros-13', ru: 'тринадцать', tr: 'tri-NA-tsat', latin: 'trinadtsat', es: 'trece', digit: 13 },
        { id: 'numeros-14', ru: 'четырнадцать', tr: 'chi-TYR-na-tsat', latin: 'chetyrnadtsat', es: 'catorce', digit: 14 },
        { id: 'numeros-15', ru: 'пятнадцать', tr: 'pit-NA-tsat', latin: 'pyatnadtsat', es: 'quince', digit: 15 },
        { id: 'numeros-16', ru: 'шестнадцать', tr: 'shys-NA-tsat', latin: 'shestnadtsat', es: 'dieciséis', digit: 16, aliasesEs: ['dieciseis'] },
        { id: 'numeros-17', ru: 'семнадцать', tr: 'sim-NA-tsat', latin: 'semnadtsat', es: 'diecisiete', digit: 17 },
        { id: 'numeros-18', ru: 'восемнадцать', tr: 'va-sim-NA-tsat', latin: 'vosemnadtsat', es: 'dieciocho', digit: 18 },
        { id: 'numeros-19', ru: 'девятнадцать', tr: 'di-vit-NA-tsat', latin: 'devyatnadtsat', es: 'diecinueve', digit: 19 },
        { id: 'numeros-20', ru: 'двадцать', tr: "DVAT-tsat'", latin: 'dvadtsat', es: 'veinte', digit: 20 }
      ]
    },
    {
      id: 'colores',
      title: 'Colores',
      glyph: 'К',
      blurb: 'Los doce que más se nombran.',
      cards: [
        { id: 'colores-01', ru: 'красный', tr: 'KRAS-nyy', latin: 'krasnyy', es: 'rojo', aliasesEs: ['roja'] },
        { id: 'colores-02', ru: 'синий', tr: 'SI-niy', latin: 'siniy', es: 'azul' },
        { id: 'colores-03', ru: 'зелёный', tr: 'zi-LYÓ-nyy', latin: 'zelyonyy', es: 'verde', aliasesRu: ['zelenyy', 'zelyony'] },
        { id: 'colores-04', ru: 'жёлтый', tr: 'ZHOL-tyy', latin: 'zheltyy', es: 'amarillo', aliasesEs: ['amarilla'], aliasesRu: ['zholtyy', 'zhelty'] },
        { id: 'colores-05', ru: 'белый', tr: 'BYE-lyy', latin: 'belyy', es: 'blanco', aliasesEs: ['blanca'] },
        { id: 'colores-06', ru: 'чёрный', tr: 'CHOR-nyy', latin: 'chernyy', es: 'negro', aliasesEs: ['negra'], aliasesRu: ['chornyy'] },
        { id: 'colores-07', ru: 'серый', tr: 'SYE-ryy', latin: 'seryy', es: 'gris' },
        { id: 'colores-08', ru: 'оранжевый', tr: 'a-RAN-zhe-vyy', latin: 'oranzhevyy', es: 'naranja' },
        { id: 'colores-09', ru: 'розовый', tr: 'RO-za-vyy', latin: 'rozovyy', es: 'rosa' },
        { id: 'colores-10', ru: 'коричневый', tr: 'ka-RICH-ni-vyy', latin: 'korichnevyy', es: 'marrón' },
        { id: 'colores-11', ru: 'фиолетовый', tr: 'fi-a-LYE-ta-vyy', latin: 'fioletovyy', es: 'morado', aliasesEs: ['violeta', 'morada'] },
        { id: 'colores-12', ru: 'голубой', tr: 'ga-lu-BOY', latin: 'goluboy', es: 'azul claro', aliasesEs: ['celeste'] }
      ]
    },
    {
      id: 'palabras',
      title: 'Palabras',
      glyph: 'Б',
      blurb: 'Verbos y sustantivos de cada día.',
      cards: [
        { id: 'palabras-01', pos: 'verb', ru: 'быть', tr: 'BYT', latin: 'byt', es: 'Ser / estar', note: 'Infinitivo. El presente de «soy» o «está» suele omitirse.' },
        { id: 'palabras-02', pos: 'verb', ru: 'хотеть', tr: 'kha-TYET', latin: 'khotet', es: 'Querer', aliasesEs: ['desear'], note: 'Desear o querer hacer algo.' },
        { id: 'palabras-03', pos: 'verb', ru: 'мочь', tr: 'MOCH', latin: 'moch', es: 'Poder', note: 'Puedo = я могу (ya ma-GU).' },
        { id: 'palabras-04', pos: 'verb', ru: 'делать', tr: 'DYE-lat', latin: 'delat', es: 'Hacer' },
        { id: 'palabras-05', pos: 'verb', ru: 'говорить', tr: 'ga-va-RIT', latin: 'govorit', es: 'Hablar' },
        { id: 'palabras-06', pos: 'verb', ru: 'понимать', tr: 'pa-ni-MAT', latin: 'ponimat', es: 'Entender', aliasesEs: ['comprender'] },
        { id: 'palabras-07', pos: 'verb', ru: 'знать', tr: 'ZNAT', latin: 'znat', es: 'Saber', aliasesEs: ['conocer'], note: 'Saber un dato y conocer a alguien.' },
        { id: 'palabras-08', pos: 'verb', ru: 'есть', tr: 'YEST', latin: 'yest', es: 'Comer / hay', aliasesRu: ['est'], note: 'Como verbo, «comer». Solo, también significa «hay».' },
        { id: 'palabras-09', pos: 'verb', ru: 'пить', tr: 'PIT', latin: 'pit', es: 'Beber', aliasesEs: ['tomar'] },
        { id: 'palabras-10', pos: 'verb', ru: 'любить', tr: 'lyu-BIT', latin: 'lyubit', es: 'Gustar / amar', note: 'Para personas, amar. Para cosas, gustar: я люблю чай.' },
        { id: 'palabras-11', pos: 'verb', ru: 'жить', tr: "ZHYT'", latin: 'zhit', es: 'Vivir' },
        { id: 'palabras-12', pos: 'verb', ru: 'работать', tr: 'ra-BO-tat', latin: 'rabotat', es: 'Trabajar' },
        { id: 'palabras-13', pos: 'verb', ru: 'читать', tr: 'chi-TAT', latin: 'chitat', es: 'Leer' },
        { id: 'palabras-14', pos: 'verb', ru: 'писать', tr: 'pi-SAT', latin: 'pisat', es: 'Escribir' },
        { id: 'palabras-15', pos: 'verb', ru: 'видеть', tr: 'VI-det', latin: 'videt', es: 'Ver' },
        { id: 'palabras-16', pos: 'verb', ru: 'смотреть', tr: 'sma-TRYET', latin: 'smotret', es: 'Mirar' },
        { id: 'palabras-17', pos: 'verb', ru: 'идти', tr: 'it-TI', latin: 'idti', es: 'Ir a pie', aliasesEs: ['caminar'], note: 'En una dirección, andando. La д casi no se oye.' },
        { id: 'palabras-18', pos: 'verb', ru: 'ехать', tr: 'YE-khat', latin: 'ekhat', es: 'Ir en transporte', aliasesEs: ['ir en coche'] },
        { id: 'palabras-19', pos: 'noun', ru: 'вода', tr: 'va-DA', latin: 'voda', es: 'agua' },
        { id: 'palabras-20', pos: 'noun', ru: 'хлеб', tr: 'KHLEP', latin: 'khleb', es: 'pan', note: 'Se escribe con б y suena p.' },
        { id: 'palabras-21', pos: 'noun', ru: 'дом', tr: 'DOM', latin: 'dom', es: 'casa' },
        { id: 'palabras-22', pos: 'noun', ru: 'друг', tr: 'DRUK', latin: 'drug', es: 'amigo', aliasesEs: ['amiga'], note: 'La г final suena k.' },
        { id: 'palabras-23', pos: 'noun', ru: 'время', tr: 'VRYE-mya', latin: 'vremya', es: 'tiempo', note: 'El tiempo que pasa, no el clima.' },
        { id: 'palabras-24', pos: 'noun', ru: 'день', tr: "DYEN'", latin: 'den', es: 'día' },
        { id: 'palabras-25', pos: 'noun', ru: 'человек', tr: 'che-la-VYEK', latin: 'chelovek', es: 'persona', aliasesEs: ['ser humano'] },
        { id: 'palabras-26', pos: 'noun', ru: 'город', tr: 'GO-rat', latin: 'gorod', es: 'ciudad', note: 'La д final suena t.' },
        { id: 'palabras-27', pos: 'noun', ru: 'книга', tr: 'KNI-ga', latin: 'kniga', es: 'libro' },
        { id: 'palabras-28', pos: 'noun', ru: 'язык', tr: 'ya-ZYK', latin: 'yazyk', es: 'idioma', aliasesEs: ['lengua'] },
        { id: 'palabras-29', pos: 'noun', ru: 'имя', tr: 'IM-ya', latin: 'imya', es: 'nombre' },
        { id: 'palabras-30', pos: 'noun', ru: 'школа', tr: 'SHKO-la', latin: 'shkola', es: 'escuela' },
        { id: 'palabras-31', pos: 'noun', ru: 'чай', tr: 'CHAY', latin: 'chay', es: 'té' },
        { id: 'palabras-32', pos: 'noun', ru: 'кофе', tr: 'KO-fe', latin: 'kofe', es: 'café', note: 'No cambia de forma.' }
      ]
    }
  ];

  root.RusoData = { alphabet: alphabet, decks: decks };
})(typeof globalThis !== 'undefined' ? globalThis : this);
